#ifndef MSG_OUT_TIME_DEF_H
#define MSG_OUT_TIME_DEF_H

// DBSMSG
#define MSG_W2DB_PASS_LOG_PLAYERBASELIST_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_PASS_LOG_QUEST_PLAYERDATA_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_PASS_LOG_CREATEROLE_TIME			5000 // 超时时间为5秒
#define MSG_W2DB_PASS_LOG_DELETEROLE_TIME			5000 // 超时时间为5秒
#define MSG_W2DB_PASS_CARD_VALIDATE_RESPONSE_TIME	5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_PLAYER_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_CREATE_PLAYER_TIME			5000 // 超时时间为5秒
#define MSG_DB2W_LOAD_REGION_PARAM_TIME				5000 // 超时时间为5秒
#define MSG_DB2W_LOAD_PLAYER_WORLD_ID_TIME			5000 // 超时时间为5秒
#define MSG_DB2W_LOAD_INIT_ENEMY_FACTION_TIME		5000 // 超时时间为5秒
#define MSG_DB2W_LOAD_INIT_COUNTRY_TIME				5000 // 超时时间为5秒
#define MSG_DB2W_LOAD_INIT_PLAYER_TIME				5000 // 超时时间为5秒

#define MSG_W2DB_SAVE_REGION_PARAM_TIME				5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_ALL_CONFEDERATIONS_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_ALL_FACTIONS_TIME				5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_INIT_ENEMY_FACTION_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_ALL_ENEMY_FACTIONS_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_CONFEDERATION_TIME			5000 // 超时时间为5秒
#define MSG_W2DB_SAVE_FACTION_TIME					5000 // 超时时间为5秒

#define MSG_W2DB_LOAD_REGION_PARAM_TIME				5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_ALL_CONFEDERATIONS_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_ALL_FACTIONS_TIME				5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_INIT_ENEMY_FACTION_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_ALL_ENEMY_FACTIONS_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_CONFEDERATION_TIME			5000 // 超时时间为5秒
#define MSG_W2DB_LOAD_FACTION_TIME					5000 // 超时时间为5秒

#define MSG_W2DB_OPER_CARD_TIME						5000 // 超时时间为5秒
#define MSG_W2DB_OPER_CITY_WAR_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_ENEMY_FACTION_TIME			5000 // 超时时间为5秒
#define MSG_W2DB_OPER_FACTION_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_GEN_VAR_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_GOOD_TIME						5000 // 超时时间为5秒
#define MSG_W2DB_OPER_PLAYER_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_REGION_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_SETUP_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_UNION_TIME					5000 // 超时时间为5秒
#define MSG_W2DB_OPER_VILLAGEWAR_TIME				5000 // 超时时间为5秒
#define MSG_W2DB_OPER_COUNTRY_TIME					5000 // 超时时间为5秒

#define MSG_W2DB_SERVER_QUEST_RECONNECTION_TIME		5000 // 超时时间为5秒
#define MSG_W2DB_SERVER_SENDSETUP_TIME				5000 // 超时时间为5秒
#define MSG_W2L_SERVER_QUEST_RECONNECTION_TIME		5000 // 超时时间为5秒

#define MSG_W2DB_PASS_GM_BANPLAYER_TIME				5000 //

// GSMSG
#define MSG_W2S_SERVER_QUEST_PING_TIME		5000 // 超时时间为5秒

#endif//MSG_OUT_TIME_DEF_H
