//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UniEditor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UNIEDITOR_DIALOG            102
#define IDD_DLGEDIT                     104
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDD_MONSTER                     131
#define IDD_NPC                         132
#define IDD_MONSTERINFO                 133
#define IDD_FILELIST                    134
#define IDD_ADDNODE                     136
#define IDR_ACCELERATOR1                138
#define IDD_DLGCOLOR                    139
#define IDB_BITMAP1                     140
#define IDR_MENU2                       141
#define IDD_COLLECTION                  143
#define IDD_COLLECTIONINFO              144
#define IDD_SIGNPOS                     145
#define IDD_ROADPOINT                   146
#define IDC_NPC_COOR_LEFT               1002
#define IDC_NPC_COOR_RIGHT              1003
#define IDC_NPC_COOR_TOP                1004
#define IDC_NPC_COOR_BOTTOM             1005
#define IDC_NPC_PICID                   1006
#define IDC_NPC_SCRIPT                  1007
#define IDC_EDIT8                       1008
#define IDC_NPC_QUANTITY                1008
#define IDC_NPC_DIRECTION               1009
#define IDC_NPC_NAME                    1010
#define IDC_MONSTER_LIST                1017
#define IDC_MONSTER_COOR_TOP            1018
#define IDC_MONSTER_COOR_RIGHT          1019
#define IDC_MONSTER_COOR_BOTTOM         1020
#define IDC_MONSTER_QUANTITY            1021
#define IDC_MONSTER_TIME_BORN           1022
#define IDC_MONSTER_TIME_START          1023
#define IDC_MONSTER_DIRECTION           1024
#define IDC_MONSTER_NO                  1025
#define IDC_MONSTER_COOR_LEFT           1026
#define IDC_MONSTER_PROBABILITY         1027
#define IDC_MONSTER_IDENTIFIER          1028
#define IDC_MONSTER_LEADER              1029
#define IDC_MONSTER_DISTANCE            1030
#define IDC_MONSTER_SCRIPT              1031
#define IDC_FILELIST                    1032
#define IDC_MONSTER_PATHID              1032
#define IDC_BUTTON1                     1033
#define IDC_SAVE                        1033
#define IDC_BUTADD                      1033
#define IDC_BTN_SAVE                    1033
#define IDC_BROWSE                      1033
#define IDC_SAVE_ALL                    1034
#define IDC_BUTADDM                     1034
#define IDC_MONSTER_TALKSCRIPT          1034
#define IDC_TALKBROWSE                  1035
#define IDC_LISTREGION                  1038
#define IDC_LISTREGIONADD               1039
#define IDC_BUTDEL                      1040
#define IDC_RADIOMONSTER                1041
#define IDC_LISTMONS                    1042
#define IDC_LISTMONSADD                 1043
#define IDC_RADIONPC                    1044
#define IDC_BUTDEL2                     1045
#define IDC_BUTDELM                     1045
#define IDC_RADIO1                      1046
#define IDC_RADIOMONINFO                1046
#define IDC_RADIOSORT                   1046
#define IDC_RADIO2                      1047
#define IDC_RADIOALL                    1047
#define IDC_LIST_LOG                    1053
#define IDC_CHECK_SHOW                  1055
#define IDC_CHECK_BORN                  1057
#define IDC_BUTTON2                     1058
#define IDC_NOSAVE                      1058
#define IDC_REFLESH                     1058
#define IDC_REFRESH                     1058
#define IDC_SCROLLBAR1                  1059
#define IDC_SCROLLBAR3                  1061
#define IDC_EDIT1                       1063
#define IDC_EDIT2                       1064
#define IDC_COLL_COOR_LEFT              1064
#define IDC_EDIT3                       1065
#define IDC_COLL_COOR_TOP               1065
#define IDC_COLL_COOR_RIGHT             1066
#define IDC_COLL_COOR_BOTTOM            1067
#define IDC_COLL_LIST                   1068
#define IDC_COLL_DIRECTION              1068
#define IDC_COLL_PROBABILITY            1069
#define IDC_COLL_NO                     1070
#define IDC_COLL_QUANTITY               1071
#define IDC_COLL_TIME_BORN              1072
#define IDC_COLL_TIME_START             1073
#define IDC_CHECK_COLL_BORN             1075
#define IDC_SIGNPOS_NO                  1076
#define IDC_SIGNPOS_X                   1077
#define IDC_SIGNPOS_Y                   1078
#define IDC_ROADSNO                     1079
#define IDC_ROADSPOINTX                 1080
#define IDC_ROADSPOINTY                 1081
#define IDC_NUMLIST                     1082
#define IDC_LIST1                       1084
#define IDC_LISTCOLL                    1085
#define IDR_POPMENU                     32771
#define ID_Menu                         32772
#define ID__32773                       32773
#define ID__32774                       32774
#define ID__ADD                         32775
#define ID__DEL                         32776
#define ID_ZOOMOUT                      32778
#define ID_ZOOMIN                       32779
#define ID_32780                        32780
#define ID_32781                        32781
#define ID_VKADD                        32782
#define ID_VKDEL                        32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
