#ifndef MSG_OUT_TIME_DEF_H
#define MSG_OUT_TIME_DEF_H

// DBSMSG
#define MSG_S2DB_LOAD_FACTION_TIME			5000 // 超时时间为5秒			
#define MSG_S2DB_LOAD_CONFEDERATION_TIME	5000 // 超时时间为5秒
#define MSG_S2DB_SAVE_FACTION_TIME			5000 // 超时时间为5秒					
#define MSG_S2DB_SAVE_CONFEDERATION_TIME	5000 // 超时时间为5秒
#define MSG_S2DB_SAVE_PLAYER_TIME			5000 // 超时时间为5秒
#define MSG_S2DB_LOAD_PLAYER_TIME			5000 // 超时时间为5秒

#define MSG_S2DB_SERVER_QUEST_RECONNECTION_TIME		5000 // 超时时间为5秒


// WSMSG
#define MSG_S2W_SERVER_QUEST_RECONNECTION_TIME		5000 // 超时时间为5秒


#endif//MSG_OUT_TIME_DEF_H
