//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by urlfile.rc
//
#define ID_BUTTON_MORE                  3
#define IDOK2                           4
#define ID_NOTAGREE                     4
#define IDCANCEL4                       8
#define IDCANCEL5                       9
#define IDCANCEL6                       10
#define IDCANCEL7                       11
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDS_ERRINVALIDURL               102
#define IDS_ERRCREATETHREAD             103
#define IDS_BTNDOWNLOAD                 104
#define IDS_BTNSTOP                     105
#define IDS_BINDSTATUS01                106
#define IDS_BINDSTATUS02                107
#define IDS_BINDSTATUS03                108
#define IDS_BINDSTATUS04                109
#define IDS_BINDSTATUS05                110
#define IDS_BINDSTATUS06                111
#define IDS_BINDSTATUS07                112
#define IDS_BINDSTATUS08                113
#define IDS_BINDSTATUS09                114
#define IDS_BINDSTATUS10                115
#define IDS_BINDSTATUS11                116
#define IDS_BINDSTATUS12                117
#define IDS_BINDSTATUS13                118
#define IDS_BINDSTATUS14                119
#define IDS_BINDSTATUS15                120
#define IDS_BINDSTATUS16                121
#define IDS_BINDSTATUS17                122
#define IDS_BINDSTATUS18                123
#define IDS_BINDSTATUS19                124
#define IDS_BINDSTATUS20                125
#define IDS_BINDSTATUS21                126
#define IDS_BINDSTATUS22                127
#define IDS_BINDSTATUS23                128
#define IDS_BINDSTATUS24                129
#define IDS_BINDSTATUS25                130
#define IDS_PROGRESS                    131
#define IDS_FAILED                      132
#define IDS_CANCELED                    133
#define IDI_ICON2                       139
#define IDB_BITMAP1                     144
#define IDS_UPDATEDVERSION              145
#define IDR_PATCH1                      146
#define IDR_PATCH2                      147
#define IDB_QUIT_CLICK                  149
#define IDB_QUIT_NORMAL                 150
#define IDR_PATCH3                      155
#define IDB_BITMAP2                     158
#define IDB_MIN_NORMAL                  158
#define IDD_DIALOG1                     159
#define IDD_DIALOG2                     166
#define IDD_DIALOG3                     169
#define IDD_DIALOG_INITIALIFNO          169
#define IDD_DIALOG_SETUP                171
#define IDD_DIALOG_CHECKALLFILE         173
#define IDB_BITMAP3                     210
#define IDB_BITMAP5                     222
#define IDD_DIALOG4                     228
#define IDD_DIALOG_SETUPSERVER          228
#define IDB_BITMAP4                     245
#define IDB_BITMAP_INGAME               245
#define IDB_BITMAP6                     247
#define IDB_BITMAP7                     250
#define IDB_BITMAP8                     270
#define IDB_BITMAP_CLOAS                270
#define IDB_BITMAP_CLOASm_bnExit        270
#define IDB_BITMAP_CLOASm_bnExitm_bnExit 270
#define IDI_ICON3                       329
#define IDI_ICON4                       331
#define IDB_BITMAP_BACKPAGE             382
#define IDI_ICON5                       386
#define IDI_ICON                        391
#define IDC_URL                         1000
#define IDC_PROGRESS                    1001
#define IDC_PROGRESS1                   1002
#define IDC_FILELIST                    1004
#define IDC_ANIMATE1                    1005
#define IDC_TOTELPROGRESS               1006
#define IDC_STATUS                      1007
#define IDC_TIMELEFT                    1008
#define IDC_TRANSFER_RATE               1009
#define IDC_TRANSFER_SIZE               1010
#define IDC_BUTTON1                     1011
#define IDC_SETUP                       1011
#define IDC_TEST                        1011
#define IDC_BUTTON_LOGIN                1011
#define IDC_INPUT                       1012
#define IDC_BUTTON2                     1012
#define IDC_BUTTON_SYSSET               1012
#define IDC_SERVERLIST                  1013
#define IDC_ADDSERVER                   1014
#define IDC_DELSERVER                   1015
#define IDC_NAME                        1016
#define IDC_COMBO1                      1017
#define IDC_COMBO_SERVERLIST            1017
#define IDC_COMBO_RES                   1017
#define IDC_CHECK_FullScreen            1018
#define IDC_COMBO_MODEL                 1018
#define IDC_CHECK_ALWAY                 1018
#define IDC_COMBO_LIGHT                 1019
#define IDC_HINTINFO                    1020
#define IDC_COMBO_SHADOW                1020
#define IDC_COMBO_TEXTURE               1021
#define IDC_HINTINFO_LOGO               1021
#define IDC_HINTINFO2                   1021
#define IDC_COMBO_WEAHTER               1022
#define IDC_COMBO_CONTROL               1023
#define IDC_EDIT1                       1024
#define IDC_COMBO_COLOR                 1024
#define IDC_COMBO_REFEASH               1025
#define IDC_SLIDER_GAMMA                1028
#define IDC_SLIDER_VIEWRANGE            1029
#define IDC_SLIDER_MUSIC                1030
#define IDC_SLIDER_SOUND                1031
#define IDC_CHECK1_MUSIC                1032
#define IDC_CHECK_SOUND                 1033
#define IDC_SLIDER_EFFECT               1035
#define IDC_CHECK1_MUSIC2               1036
#define IDC_CHECK_WINDOW                1036
#define ID_OK                           1038
#define ID_NO                           1039
#define IDC_STATIC_TEXT                 1040
#define IDC_BUTTON_CHECKALLFILE         1041
#define IDC_STATIC_                     1043
#define IDC_STATIC_DISPLAYINFO          1043
#define IDC_HINTINFO_PROTOCONTEXT       1045
#define IDC_BUTTON_CHECKSYS             1046
#define IDC_BUTTON_CHECKSYSCON          1046
#define IDC_DOWNLOADHINTINFO            1047
#define IDC_HOTKEY1                     1048
#define IDC_STATIC1                     1049
#define IDC_EXPLORER1                   1052
#define IDC_BUTTON3                     1053
#define IDC_BUTTON_FIRSTPAGE            1053
#define IDC_CHECK_SPEECH                1054
#define IDC_SLIDER_Speech               1055
#define IDC_CHECK_FOOTSTEP              1056
#define IDC_BUTTON_NEWPLAYER            1057
#define IDC_BUTTON_GAMEINFO             1058
#define IDC_BUTTON_FORUM                1059
#define IDC_BUTTON_REGIST               1060
#define IDC_BUTTON_PAYMENT              1061
#define IDC_BUTTON_SERVE                1062
#define IDC_EXPLORER2                   1063
#define IDC_BUTTON4                     1064
#define IDC_BUTTON_LONGING              1064
#define IDC_BUTTON_CACEL                1065
#define IDC_BUTTON_WIRE                 1066
#define IDC_BUTTON_NET                  1067
#define IDC_BUTTON5_CHOOSER             1068
#define IDC_BUTTON_CHOOSER2             1069
#define IDC_CHECK_UPDATEONFOUCE         1074
#define IDC_BUTTON_NEW                  1076
#define IDC_BUTTON_ZHANGHAO             1077
#define IDC_BUTTON_DOWNLOAD             1078
#define IDC_BUTTON_KEFU                 1079
#define IDC_BUTTON_LUNTAN               1080
#define IDS_HTTPDOWNLOAD_BYTES          57345
#define IDS_HTTPDOWNLOAD_KILOBYTES      57346
#define IDS_HTTPDOWNLOAD_MEGABYTES      57347
#define IDS_HTTPDOWNLOAD_SECONDS        57348
#define IDS_HTTPDOWNLOAD_MINUTES        57349
#define IDS_HTTPDOWNLOAD_MINUTES_AND_SECONDS 57350
#define IDS_HTTPDOWNLOAD_BYTESPERSECOND 57351
#define IDS_HTTPDOWNLOAD_KILOBYTESPERSECOND 57352

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        392
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
