//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameTest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GAMETEST_DIALOG             102
#define IDD_PROPPAGE_MONSTER_INFO       103
#define IDD_PROPPAGE_SKILL_INFO         104
#define IDD_PROPPAGE_GAMEINFO           107
#define IDD_PROPPAGE_TESTSCRIPT         108
#define IDD_PROPPAGE_REGION_INFO        109
#define IDD_PROPPAGE_PLAYER_INFO        110
#define IDR_MAINFRAME                   128
#define IDR_TestCase_MENU               133
#define IDR_MENU_Tools                  140
#define IDD_PROPPAGE_Region_Goods_Info  145
#define IDR_TreeRootMenu                153
#define IDD_DIALOG_AddName              154
#define IDD_DriveClient                 155
#define IDD_PROPPAGE_SKILL              156
#define IDD_DIALOG_AllTest              157
#define IDD_DIALOG1                     158
#define IDD_PROPPAGE_LINKMAN            159
#define IDD_DIALOG_GOODS_TEST           160
#define IDD_PROPPAGE_AC_ANSWER          161
#define IDR_MENU_TRAY                   162
#define IDB_SKIN_MSN                    163
#define IDR_4001                        168
#define IDD_DIALOG_TESTRESLUT           169
#define IDD_DIALOG_TESTRESULT           169
#define IDD_PROPPAGE_MAIL               400
#define IDC_RunScript                   1000
#define IDC_TAB_MAIN                    1002
#define IDC_TREE_TEST_CASE              1004
#define IDC_EDIT_INPUT_INFO             1006
#define IDC_EDIT_OUTPUT_INFO            1009
#define IDC_STATIC_PLAYE_NAME           1010
#define IDC_STATIC_PALYER_ID            1011
#define IDC_EDIT_SCRIPT_EDIT            1012
#define IDC_STATIC_PLAYE_Hp             1012
#define IDC_EDIT_SCRIPT_ERROR_INFO      1013
#define IDC_STATIC_PLAYE_MaxHp          1013
#define IDC_BUTTON_CHECK_SCRIPT_SYNTAX  1014
#define IDC_STATIC_PLAYE_Mp             1014
#define IDC_STATIC_PLAYER_X             1015
#define IDC_STATIC_PLAYE_MaxMp          1015
#define IDC_STATIC_PLAYER_Y             1016
#define IDC_STATIC_PLAYER_UpExp         1016
#define IDC_STATIC_PLAYE_NAME2          1017
#define IDC_STATIC_PLAYE_SocketID       1018
#define IDC_STATIC_PLAYER_Exp           1019
#define IDC_STATIC_PLAYER_Money         1020
#define IDC_STATIC_PLAYER_Level         1021
#define IDC_SKILL_LIST                  1022
#define IDC_STATIC_PLAYER_Sex           1022
#define IDC_SKILL_EDIT                  1023
#define IDC_STATIC_PLAYER_Stamina       1023
#define IDC_Goods_List                  1024
#define IDC_OccupSkillList              1024
#define IDC_STATIC_PLAYER_Occupation    1025
#define IDC_STATIC_RegionID             1026
#define IDC_STATIC_PLAYER_Energy        1026
#define IDC_SaveScript                  1027
#define IDC_STATIC_PLAYER_CountryContribute 1027
#define IDC_STATIC_PLAYER_UpgradeExp    1028
#define IDC_SaveScript2                 1028
#define IDC_UpdateScript                1028
#define IDC_STATIC_PLAYER_SpouseID      1029
#define IDC_DisConnect                  1029
#define IDC_STATIC_PLAYER_RankOfNobility 1030
#define IDC_STATIC_PLAYER_RanOfNobCredit 1031
#define IDC_LIST_Monster                1031
#define IDC_STATIC_PLAYER_Country       1032
#define IDC_LIST_Npc                    1032
#define IDC_LIST_RegionGoods            1032
#define IDC_Occup                       1033
#define IDC_StartCDKey                  1042
#define IDC_EndCDKey                    1043
#define IDC_StartLogin                  1045
#define IDC_StartLogin2                 1046
#define IDC_CLOSE_GT                    1046
#define IDC_ScriptName                  1047
#define IDC_CheckOne                    1048
#define IDC_ShowScriptPath              1050
#define IDC_AddName                     1052
#define IDC_AddTitle                    1053
#define IDC_SHowInfo                    1055
#define IDC_ScriptManage                1056
#define IDC_BUTTON1                     1056
#define IDC_BUTTON3                     1057
#define IDC_DriveClient                 1057
#define IDC_EDIT1                       1057
#define IDC_EDIT2                       1058
#define IDC_STATIC_ShowAmount           1058
#define IDC_COMBO1                      1059
#define IDC_COMBO_ServerList            1059
#define IDC_COMBO_OCCU                  1059
#define IDC_COMBO_TestType              1060
#define IDC_EDIT_Timer                  1062
#define IDC_TAB_PAGE                    1063
#define IDC_EDIT_Timer2                 1063
#define IDC_EDIT_DelayTime              1063
#define IDC_EDIT_POSY                   1064
#define IDC_RADIO_ATTACK_HIGH           1065
#define IDC_RADIO_ATTACK_LOW            1066
#define IDC_CHECK_SKILL1                1068
#define IDC_CHECK_SKILL2                1069
#define IDC_CHECK_SKILL3                1070
#define IDC_EDIT_SKILLID1               1071
#define IDC_EDIT_SKILLID2               1072
#define IDC_EDIT_SKILLID3               1073
#define IDC_EDIT_SKILLID4               1074
#define IDC_RADIO_WEAPON1               1075
#define IDC_RADIO_WEAPON2               1076
#define IDC_RADIO_WEAPON3               1077
#define IDC_RADIO_WEAPON4               1078
#define IDC_RADIO_WEAPON6               1079
#define IDC_RADIO_WEAPON7               1080
#define IDC_RADIO_WEAPON5               1081
#define IDC_COMBO_SkillIP               1084
#define IDC_EDIT_Skill                  1085
#define IDC_EDIT_SkillVersion           1085
#define IDC_EDIT_REGIONID               1086
#define IDC_EDIT_POSX                   1087
#define IDC_SkillStartCDKey             1088
#define IDC_SkillEndCDKey               1089
#define IDC_EDIT_SkillTimer             1090
#define IDC_BUTTON_SkillStart           1091
#define IDC_TAB_TypePage                1092
#define IDC_STATIC_MailLogin2           1096
#define IDC_EDIT_MAIL_StartCdKey        1097
#define IDC_EDIT_MAIL_EndCdkey          1098
#define IDC_EDIT_MAIL_MsgTimer          1099
#define IDC_EDIT_MAIL_SeverSub          1100
#define IDC_COMBO_MAILSever             1101
#define IDC_BUTTON_MailStart            1102
#define IDC_EDIT_MAIL_REGION            1103
#define IDC_EDIT_MAIL_SendDoodsName     1105
#define IDC_EDIT_MAIL_SendMoney         1106
#define IDC_EDIT_MAIL_SendName          1107
#define IDC_EDIT_MAIL_SendGoodsNum      1108
#define IDC_EDIT_MAIL_SendType          1109
#define IDC_EDIT_MAIL_SendRepeatNum     1111
#define IDC_EDIT_MAIL_SendMsgRepeatNum  1112
#define IDC_EDIT_MAIL_RejectProbability 1117
#define IDC_EDIT_MAIL_DeleteProbability 1118
#define IDC_EDIT_MAIL_ExitProbability   1120
#define IDC_EDIT_MAIL_POSX              1121
#define IDC_EDIT_MAIL_ExitProbability2  1121
#define IDC_EDIT_LINKMAN_DelProbability 1121
#define IDC_EDIT_MAIL_POSY              1122
#define IDC_EDIT_LINKMAN_MoveProbability 1122
#define IDC_CHECK_MAIL_SEND             1124
#define IDC_CHECK_MAIL_Reject           1125
#define IDC_CHECK_MAIL_RepeatSendName   1126
#define IDC_CHECK_MAILREC               1127
#define IDC_CHECK_MAIL_Delete           1128
#define IDC_CHECK_MAIL_GetGoods         1129
#define IDC_CHECK_MAIL_AgreedPay        1130
#define IDC_CHECK_MAIL_GetMoney         1131
#define IDC_CHECK_MAIL_ExitClient       1132
#define IDC_CHECK_MAIL_RepeatSendMsg    1133
#define IDC_EDIT_LINKMAN_REGION         1133
#define IDC_EDIT_LINKMAN_POSX           1134
#define IDC_EDIT_LINKMAN_POSY           1135
#define IDC_EDIT_LINKMAN_StartCdKey     1136
#define IDC_EDIT_LINKMAN_EndCdkey       1137
#define IDC_EDIT_LINKMAN_MsgTimer       1138
#define IDC_COMBO_LINKMAN_SeverIP       1139
#define IDC_EDIT_LINKMAN_SeverSub       1140
#define IDC_BUTTON_LINKMAN_START        1141
#define IDC_CHECK_LINKMAN_SendAdd       1143
#define IDC_CHECK_LINKMAN_ResponseAdd   1144
#define IDC_CHECK_LINKMAN_SendMove      1145
#define IDC_CHECK_LINKMAN_Del           1146
#define IDC_CHECK_LINKMAN_ExitClient    1147
#define IDC_EDIT_LINKMAN_ExitProbability 1148
#define IDC_CHECK1                      1149
#define IDC_CHECK_RANDOMPOS             1149
#define IDC_CHECK2                      1150
#define IDC_CHECK3                      1151
#define IDC_CHECK4                      1152
#define IDC_EDIT_ACC_REGION             1152
#define IDC_CHECK5                      1153
#define IDC_CHECK6                      1154
#define IDC_EDIT_ACC_POSX               1155
#define IDC_EDIT_ACC_POSY               1156
#define IDC_EDIT_ACC_StartCdKey         1157
#define IDC_EDIT_ACC_EndCdkey           1158
#define IDC_EDIT_ACC_MsgTimer           1159
#define IDC_EDIT_ACC_SeverSub           1160
#define IDC_BUTTON_ACC_START            1161
#define IDC_COMBO_ACC_SeverIP           1162
#define IDC_ACC_CHECK_Answer            1163
#define IDC_ACC_CHECK_SAFE              1164
#define IDC_ACC_CHECK_CopyMsg           1165
#define IDC_ACC_CHECK_CopySend          1166
#define IDC_ACC_CHECK_ExitClient        1167
#define IDC_CHECK_SKILL_ACCAnswer       1168
#define IDC_CHECK_PtToken               1169
#define IDC_STATIC_CDKeyStart           1170
#define IDC_STATIC_CDKeyEnd             1171
#define IDC_STATIC_SKILL_START_CDKEY    1172
#define IDC_STATIC_SKILL_END_CDKEY      1173
#define IDC_CHECK_MAIL_PT_LOGIN         1174
#define IDC_STATIC_strStartCDkey        1176
#define IDC_STATIC_strEndCDkey          1177
#define IDC_CHECK_LINKMAN_PT_LOGIN      1178
#define IDC_STATIC_LINKMAN_strStartCDkey 1179
#define IDC_STATIC_LINKMAN_strEndCDkey  1180
#define IDC_CHECK_ACA_PT_LOGIN          1181
#define IDC_STATIC_ACC_strStartCDkey    1182
#define IDC_STATIC_ACC_strEndCDkey      1183
#define IDC_STATIC_SERVER               1184
#define IDC_COMBO_SKILL_IP              1185
#define IDC_PLAYERLEVEL                 1186
#define IDC_PLAYERRGNX                  1187
#define IDC_MAXSTATE                    1188
#define IDC_EQUIPWEAPON                 1189
#define IDC_THIRDOCCU                   1190
#define IDC_COMBO_PLAYEROCCU            1192
#define IDC_COMBO_OccuList              1192
#define IDC_COMBO_RegionList            1193
#define IDC_PLAYERRGNY                  1194
#define IDC_COMBO_TDLG_PROJNAME         1195
#define IDC_STATIC_WORKPATH             1196
#define IDC_BUTTON_TESTDLG_CHOOSEPATH   1197
#define IDC_STATIC_TESTRS               1200
#define IDC_EDIT_TESTRT                 1201
#define IDC_STATIC_ShowClientNum        1202
#define ID_AddCase                      32775
#define ID_AddScript                    32779
#define ID_DelScript                    32782
#define ID_TOOLS_32793                  32793
#define ID_CASE_STOP                    32864
#define ID_CASE_START                   32865
#define ID_Menu                         32866
#define ID__32867                       32867
#define ID__32868                       32868
#define ID_TRAY_SHOW                    32869
#define ID_TRAY_HIDE                    32870
#define ID_TRAY_EXIT                    32871
#define ID_Menu32872                    32872
#define ID_TRAY_ALL                     32873
#define ID_GAMETEST_32874               32874
#define ID_GAMETEST_32875               32875
#define ID_GAMETEST_32876               32876
#define ID_TRAY_SHOWINFO                32877
#define ID_GAMETEST_32878               32878
#define ID_VIEW_SHOWINFO                32879
#define ID_VIEW_SHOWRESLUT              32880

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32881
#define _APS_NEXT_CONTROL_VALUE         1203
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
