#ifndef __WND_MSG_DEF__
#define __WND_MSG_DEF__

//自定义客户端树控件ID
#define IDT_GAME_CLIENT			10000

#define GAME_CLIENT_TREE_SELCHANGED WM_USER+1000
#define DISPLAY_INFO_RESET_GAME_CLIENT WM_USER+1001

#endif